global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'NServiceBus Telemetry'
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets:
        - '192.168.0.114:9184'
